repos:

    -   repo: https://github.com/psf/black
        rev: 22.1.0
        hooks:
        - id: black
          language: system
          files: ^src/
          types: [file, python]
          exclude: ^features/steps/test_starter|^kedro/templates/
          args: ["--line-length=120"]
          entry: black

    -   repo: https://github.com/asottile/add-trailing-comma
        rev: v2.2.1
        hooks:
        -   id: add-trailing-comma

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace

    -   repo: local
        hooks:

        -   id: flake8
            name: flake8
            description: Flake8 linting check
            files: ^src/
            exclude: __pycache__|env|venv|data
            entry: flake8
            language: python
            types: [python]

        -   id: pylint
            name: pylint
            description: Pylint linting check
            files: ^src/
            entry: pylint
            language: system
            types: [python]
            args: ["--rcfile=pylint.rc", "--disable=E0402,E0611"]

    # # NOTE: this one is optional (removing outputs of jupyter)
    # -   repo: https://github.com/kynan/nbstripout
    #     rev: 0.5.0
    #     hooks:
    #     -    id: nbstripout
    #          files: ".ipynb$"
